[2022-01-11 19:01:47,706] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 19:01:47,714] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 19:01:47,714] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:01:47,714] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-11 19:01:47,714] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:01:47,792] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): accurate> on 2022-01-10 00:00:00+00:00
[2022-01-11 19:01:47,797] {standard_task_runner.py:52} INFO - Started process 4971 to run task
[2022-01-11 19:01:47,803] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-01-10T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphi2z4pum', '--error-file', '/tmp/tmp8ad7y3c1']
[2022-01-11 19:01:47,803] {standard_task_runner.py:77} INFO - Job 23: Subtask accurate
[2022-01-11 19:01:47,900] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-01-10T00:00:00+00:00 [running]> on host 40c4c8725776
[2022-01-11 19:01:48,147] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-10T00:00:00+00:00
[2022-01-11 19:01:48,148] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-11 19:01:48,149] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-01-11 19:01:48,169] {subprocess.py:85} INFO - Output:
[2022-01-11 19:01:48,178] {subprocess.py:89} INFO - accurate
[2022-01-11 19:01:48,179] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-11 19:01:48,284] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220110T000000, start_date=20220111T190147, end_date=20220111T190148
[2022-01-11 19:01:48,385] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 19:01:48,519] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
