[2022-01-11 19:03:35,435] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: my_dag.inaccurate scheduled__2022-01-10T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'choose_best_model'}
[2022-01-11 19:03:35,533] {local_task_job.py:99} INFO - Task is not able to be run
[2022-01-11 19:03:47,513] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 19:03:47,537] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 19:03:47,538] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:03:47,538] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-11 19:03:47,538] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:03:47,732] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): inaccurate> on 2022-01-10 00:00:00+00:00
[2022-01-11 19:03:47,736] {standard_task_runner.py:52} INFO - Started process 5057 to run task
[2022-01-11 19:03:47,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-01-10T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpgfmsevx2', '--error-file', '/tmp/tmpir5kt6nu']
[2022-01-11 19:03:47,759] {standard_task_runner.py:77} INFO - Job 31: Subtask inaccurate
[2022-01-11 19:03:47,887] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-01-10T00:00:00+00:00 [running]> on host 40c4c8725776
[2022-01-11 19:03:48,095] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-10T00:00:00+00:00
[2022-01-11 19:03:48,096] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-11 19:03:48,096] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-01-11 19:03:48,104] {subprocess.py:85} INFO - Output:
[2022-01-11 19:03:48,112] {subprocess.py:89} INFO - inaccurate
[2022-01-11 19:03:48,112] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-11 19:03:48,209] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220110T000000, start_date=20220111T190347, end_date=20220111T190348
[2022-01-11 19:03:48,307] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 19:03:48,484] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
